# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raspberry/Interface/Designs/alertDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alertDialog(object):
    def setupUi(self, alertDialog):
        alertDialog.setObjectName("alertDialog")
        alertDialog.resize(900, 140)
        alertDialog.setStyleSheet("*{\n"
"font: 20pt \"Ubuntu\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(alertDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(alertDialog)
        self.widget.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-left: 40px solid;\n"
"border-color: rgb(255, 210, 47);\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(40, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:none;\n"
"    font: 40pt \"Arial Rounded MT Bold\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(76, 165, 34);\n"
"    background-color: rgb(170, 0, 0);\n"
"}")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("border:none;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(5, 5, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(40, 0, 111, 31))
        self.label.setStyleSheet("background-color: none;")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 21, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.widget_3, 0, 0, 1, 1)
        self.messageLabel = QtWidgets.QLabel(self.widget_2)
        self.messageLabel.setStyleSheet("background-color: none;")
        self.messageLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.gridLayout_3.addWidget(self.messageLabel, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(0, 20)
        self.gridLayout_3.setRowStretch(1, 50)
        self.gridLayout_2.addWidget(self.widget_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("border:none;\n"
"border-right: 1px solid;\n"
"border-color: rgb(216, 216, 216);\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 80)
        self.gridLayout_2.setColumnStretch(2, 20)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(alertDialog)
        self.pushButton.clicked.connect(alertDialog.clearAlert) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(alertDialog)

    def retranslateUi(self, alertDialog):
        _translate = QtCore.QCoreApplication.translate
        alertDialog.setWindowTitle(_translate("alertDialog", "Dialog"))
        self.pushButton.setText(_translate("alertDialog", "X"))
        self.label.setText(_translate("alertDialog", "Alerta"))
        self.label_3.setText(_translate("alertDialog", "!"))
        self.messageLabel.setText(_translate("alertDialog", "Desconexión con camara(s): #"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    alertDialog = QtWidgets.QDialog()
    ui = Ui_alertDialog()
    ui.setupUi(alertDialog)
    alertDialog.show()
    sys.exit(app.exec_())
